### ISSUE TITLE
Parameters in weights file do not match

### ISSUE THREAD

**Issue by chenxi-Guo** [francescotonini/human-gaze-target-detection-transformer#3]
![image](https://github.com/francescotonini/human-gaze-target-detection-transformer/assets/109503570/a22eacec-853e-4d58-9836-855b53f2489a)

**Comment by weiyingxue** [comment]
I have same question

**Comment by weiyingxue** [comment]
请问您解决了嘛

**Comment by chenxi-Guo** [comment]
我没有解决



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 22, 2024 15:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [francescotonini/human-gaze-target-detection-transformer]Parameters in weights file do not match (Issue #3)




 
请问您解决了嘛
