### ISSUE TITLE
Regarding the issue of model accuracy

### ISSUE THREAD

**Issue by chenwenhe11** [francescotonini/human-gaze-target-detection-transformer#4]
Why is the accuracy of the model I evaluated after training much lower than the accuracy reported in the paper? Have you experienced this situation?

**Comment by francescotonini** [comment]
Hi, can you give me more context? What did you train, and which results did you get? Thanks.

**Comment by chenwenhe11** [comment]
thank you for your reply. I used the default parameters of the model after training, and the test results are as follows:

**Comment by francescotonini** [comment]
Try to increase the weight of the heatmap loss [here](https://github.com/francescotonini/human-gaze-target-detection-transformer/blob/main/configs/criterion/hgttr.yaml#L16) to 100, it should fix your issue.
